### ISSUE TITLE
Can you make a BepInEx 6 version?

### ISSUE THREAD

**Issue by saerdodus** [johnytoxic/CSL2DemandControl#3]
Thank you very much for your great module, but many of the modules I use run under BepInEx 6, and would like to know if you can make a BepInEx 6 version of this module, thank you very much!

**Comment by Peter-JY** [comment]
Since BenInEx 5 will no longer have functional upgrades, I hope this mod can have a BepInEx 6 version, and I'm looking forward to the new BepInEx 6 version of this mod as well. XD

**Comment by johnytoxic** [comment]
How are you using/installing this and other mods? My primary focus was to make it available through the Thunderstore app. Since that only ships with BepInEx 5, I'm using this version. I assume all the other mods on that platform also use v5.

I'll have a look into how I can make this work with v6 as well; maybe in a parallel branch.

**Comment by saerdodus** [comment]
I'm installing the mod manually now

In addition to Thunderstore, I search and install mods on the following platforms, which also have a lot of great mods

https://www.nexusmods.com/citiesskylines2/mods

https://paradoxmods.net/forums/10-cities-skylines-ii-mods/

https://www.cslbbs.net/resources/categories/mod.3/

https://bbs.3dmgame.com/forum.php?mod=forumdisplay&fid=3877&filter=typeid&typeid=50030

**Comment by johnytoxic** [comment]
BepInEx 6 is still in development and hasn't been officially released, yet.

I've rebuild the mod against BepInEx 6 and attached it to the [latest release](https://github.com/johnytoxic/CSL2DemandControl/releases/tag/beta-1.0.2). Could you please verify whether that's working for you?

**Comment by arc130** [comment]
Hi, I've installed the BepInEx 6 version in the latest release, unfortunately it can't load.
The BepInEx console showed, it did not recognize newly installed mods.

```
[Message: Preloader] BepInEx 6.0.0-be.688 - Cities2
[Message: Preloader] Built from commit 49015217f3becf052d33fa4658ac19229f5daa3a
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   : Preloader] Running under Unity 2022.3.7f1
[Info   : Preloader] CLR runtime version: 4.0.30319.42000
[Info   : Preloader] Supports SRE: True
[Message: Preloader] Preloader started
[Info   :AssemblyPatcher] Loaded 1 patcher type from [BepInEx.Unity.Mono.Preloader 6.0.0.0]
[Info   : Preloader] 1 patcher plugin loaded
[Info   : Preloader] 179 assemblies discovered
[Message:AssemblyPatcher] Executing 1 patch(es)
[Message: Preloader] Preloader finished
[Message:   BepInEx] Chainloader initialized
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [ModByLucifer 4.2.0]
[Info   :   BepInEx] Loading [Unlock All Tiles Mod 1.1.1]
```

**Comment by johnytoxic** [comment]
This is obsolete now, because of the launch of the official Paradox Mods store (see [announcement](https://forum.paradoxplaza.com/forum/threads/modding-wavelet-patch-1-1-0f1.1640000/)).

[I've published the mod](https://github.com/johnytoxic/CSL2DemandControl/issues/12#issuecomment-2041409764) to the official store: https://mods.paradoxplaza.com/mods/77901/Windows
